apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: {{ .Values.replicaCount.nginx }}
  selector:
    matchLabels:
      app: nginx-backend
  template:
    metadata:
      labels:
        app: nginx-backend
    spec:
      containers:
      - name: nginx
        image: {{ .Values.images.nginx }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
